###
GET http://localhost:3000/

### Consulta de Configuración
GET http://localhost:3000/api/v1/config/configuration


### Creación de configuración
POST http://localhost:3000/api/v1/config/configuration
content-type: application/json

{
    "nameApp": "ShopBeer",
	"versionWeb": "1.0.0",
	"versionApp": "1.0.0",
	"api": "https://shop-beer-back.onrender.com"
}

### Consulta de notificaciones.
GET http://localhost:3000/api/v1/config/notifications


### Creación de notificación.
POST http://localhost:3000/api/v1/config/notifications
content-type: application/json

{
    "name": "Mantenimiento",
    "description": "Habrá mantenimiento el día 15 de enero.",
    "isactive": 1
}

###
POST http://localhost:3000/api/v1/user/login

{
    "name": "Mantenimiento",
    "description": "Habrá mantenimiento el día 15 de enero.",
    "isactive": 1
}


###
POST http://localhost:3000/api/v1/user/register
content-type: application/json

{
    "id": 1,
    "name": "Habrá mantenimiento el día 15 de enero.",
    "isactive": 1
}


### OBTENER TODAS LAS LOCALIZACIONES 
GET http://localhost:3000/api/v1/user/getLocations


### NUEVA LOCALIZACIÓN 
POST http://localhost:3000/api/v1/user/newLocation
content-type: application/json

{
    "name": "Vistas del Río 1",
    "description": "Calle 138C sur 14K-26",
    "isavailable": 1
}